# Generated by Django 4.2.17 on 2025-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KayakTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255, unique=True, verbose_name='Lead ID')),
                ('lead_date', models.DateTimeField(verbose_name='Lead Date')),
                ('lead_checkin', models.DateTimeField(verbose_name='Lead Check-in')),
                ('lead_checkout', models.DateTimeField(verbose_name='Lead Checkout')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hotel Country')),
                ('hotel_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hotel City')),
            ],
            options={
                'verbose_name': 'Kayak Transaction',
                'verbose_name_plural': 'Kayak Transactions',
            },
        ),
    ]
