# Generated by Django 4.2.17 on 2025-01-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_transaction_boom_score_delta_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KayakTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255, unique=True, verbose_name='Lead ID')),
                ('lead_date', models.DateTimeField(verbose_name='Lead Date')),
                ('lead_checkin', models.DateTimeField(verbose_name='Lead Check-in')),
                ('lead_checkout', models.DateTimeField(verbose_name='Lead Checkout')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Kayak Transaction',
                'verbose_name_plural': 'Kayak Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='import_export.kayaktransaction')),
            ],
            options={
                'verbose_name': 'Transaction Metadata',
                'verbose_name_plural': 'Transaction Metadata',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
