# Generated by Django 4.2.17 on 2025-01-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0003_kayaktransaction_transactionmetadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionMetadata',
        ),
    ]
