# Generated by Django 4.2.17 on 2025-01-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0004_delete_transactionmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayaktransaction',
            name='hotel_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kayaktransaction',
            name='hotel_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kayaktransaction',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
